# Generated by Django 4.2.5 on 2023-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_toy'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='toys',
            field=models.ManyToManyField(to='main_app.toy'),
        ),
        migrations.AlterField(
            model_name='finch',
            name='age',
            field=models.IntegerField(),
        ),
    ]
